// <auto-generated />
namespace BigSchool_2090694874.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _4874 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4874));
        
        string IMigrationMetadata.Id
        {
            get { return "202303150714204_ 4874"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
